### ISSUE TITLE
Summary

### ISSUE THREAD

**Issue by miraydamartinez** [jegarin/sql-scratch-capstone-turn-in#3]
### Criteria 1: Report: Are conclusions clear and supported by evidence in all eight answers?
* _Score Level:_ 2 (Approaches Expectations)
* _Comment(s):_ All conclusions are clearly supported by evidence (in the form of queries), great job! However, you don't include tables in your project which makes it difficult for people with a non-tech background to understand how you got to your conclusions. Friendly reminder that visuals go a long way in presentations!
 
### Criteria 2: Query Accuracy: Do queries do what they were supposed to do?
* _Score Level:_ 4 (Exceeds Expectations)
* _Comment(s):_ It seems you have more than a solid understanding of how to use and write queries to analyze large-scale datasets! Nice!
 
### Criteria 3: Query Formatting
* _Score Level:_ 3 (Meets Expectations)
* _Comment(s):_ For the most part, your queries are formatted according to SQL lessons, but there are a few occasions where multiple columns and expressions appear on the same line. Remember to always start a new line when you are switching from one expression to another or are adding in another column. _Example_: 
SELECT COUNT(*),
  COLUMN_NAME1,
  COLUMN_NAME2,
FROM table_name
 
### Criteria 4: Understanding underlying concepts and terminology
* _Score Level:_ 4 (Exceeds Expectations)
* _Comment(s):_ Your conclusions show a strong understanding of SQL concepts. Your ability to interpret data in your conclusions is a great skill, especially when visuals are absent and you do this fluently. 

 ### Overall Score: 13/16
Overall, you did a great job! You utilized the skills learned from SQL lessons to analyze information for a company and provide actionable insights for their marketing methods. Remember to always structure your queries according to SQL styling guides and provide tables to help back up your conclusions in addition to queries.

**Comment by jegarin** [comment]
Thank you @miraydamartinez. !
I will remind myself to include tables. VIsual are definitely important to people understand my conclusions.
